<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MultiLsTokenServer.Grpc.Api</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.36.2" />
    <PackageReference Include="Grpc.Net.Client" Version="2.84.0" />
    <PackageReference Include="Grpc.Tools" Version="2.84.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MultiLsTokenServer.Domain\MultiLsTokenServer.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\common.proto" />
    <Protobuf Include="Protos\diagnostic.proto" />
    <Protobuf Include="Protos\vendingElectricity.proto" />
    <Protobuf Include="Protos\vendingWater.proto" />
    <Protobuf Include="Protos\vendingGas.proto" />
    <Protobuf Include="Protos\vendingTime.proto" />
    <Protobuf Include="Protos\management.proto" />
    <Protobuf Include="Protos\meterTestDisplay.proto" />
  </ItemGroup>

</Project>
